version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: detailed
    filename: data/logs/emotionless_options.log
    encoding: utf8

loggers:
  emotionless_options:
    level: INFO
    handlers: [console, file]
    propagate: false

  emotionless_options.scrapers:
    level: DEBUG
    handlers: [console, file]
    propagate: false

  emotionless_options.analysis:
    level: DEBUG
    handlers: [console, file]
    propagate: false

  emotionless_options.sentiment:
    level: DEBUG
    handlers: [console, file]
    propagate: false

root:
  level: INFO
  handlers: [console] 